### ISSUE TITLE
perturb chi writes an EMPTY product on every profile: chi.mixing_use_qc_fallback leaks into the _compute_chi splat

### ISSUE THREAD

**Issue by mousebrains** [mousebrains/turbulence#184]
## Summary

On current `main` (d86c62d), `perturb run` produces **no chi at all**. Every
profile raises

```
TypeError: _compute_chi() got an unexpected keyword argument 'mixing_use_qc_fallback'
```

and the run still exits reporting stage success.

## Why it is worse than a crash

`pipeline.py` catches per-profile exceptions, logs them, and continues. So the
observable behaviour is:

- a `chi_NN/` output directory that is **created and left empty**,
- a run summary reading `Pipeline complete with 0 stage failure(s) and N file error(s)`,
- exit status 0, and the binning/combo stages happily assembling the rest.

On ARCTERX-2022 Interior that is **1330 profiles and zero chi files**, from a
run that reported success. Anyone not reading the error lines gets a silently
truncated product.

## Root cause

`chi_kwargs` is built by **blocklist** — the whole `chi:` config section is
splatted into `_compute_chi(**kwargs)` minus a hardcoded exclusion tuple
(`src/odas_tpw/perturb/pipeline.py`). #182 added the `chi.mixing_use_qc_fallback`
config key (consumed by `_add_mixing_quantities`, never a `_compute_chi`
parameter) without adding it to that tuple.

So **any** new `chi:` key that is not a `_compute_chi` parameter breaks all chi.
The epsilon splat carries a comment warning about precisely this failure mode:

> Leaving them in the splat is a TypeError that the per-profile handler turns
> into "every profile errored, diss/ empty" rather than a traceback.

The chi splat had no equivalent guard, and nothing tested the invariant.

## Reproduce

Any config with `chi.enable: true`:

```
perturb run -c perturb.yaml --stdout <one .p file>
...
Done processing ARC1A001.P: 5 profiles (5 dissipation, 0 chi) in 4.9s
Pipeline complete with 0 stage failure(s) and 21 file error(s).
  file error:  : ARC1A001.P: chi ...prof001.nc: _compute_chi() got an unexpected keyword argument 'mixing_use_qc_fallback'
```

Note `5 dissipation, **0 chi**` and the `0 stage failure(s)`.

## Scope

Audited both splats against the callee signatures:

| section | leaked keys |
|---|---|
| `epsilon` | none |
| `chi` | `mixing_use_qc_fallback` |

(The duration keys `fft_sec`/`diss_sec`/`overlap_sec` are stripped upstream by
`resolve_window_config`, so they are not leaks.)

Introduced in 43617d7 (#182). Affects every `perturb` chi run since.

## Fix

PR to follow: add the key to the exclusion list, hoist both lists to
module-level constants, and add `tests/test_kwarg_splat_guard.py` asserting
that what survives each filter is a subset of the callee's real signature —
for both stages, so neither can regress this way again.

## Follow-up worth considering

Separately from the fix: a per-profile handler that turns a systematic
`TypeError` into an empty product plus exit 0 is the thing that made this
invisible. Worth deciding whether a stage where **100% of profiles failed**
should be a stage failure rather than a file-error tally.

**Comment by mousebrains** [comment]
Follow-up addressed in #186 (stacked on #185): a per-profile stage that produced an empty product while profiles exist is now a stage error, so the run exits non-zero instead of reporting success.

Two notes for anyone reading back:

- The class is `PipelineResult`, not `PipelineOutcome` — corrected in the description above.
- The check counts the product **directory**, not the per-file result lists. Counting results would fail every fully-cached re-run, where each file is served from cache and returns no paths while the products sit complete on disk.
